"""followers

Revision ID: 989f655b9647
Revises: cfbba8e8e9c8
Create Date: 2024-08-23 12:26:13.855304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989f655b9647'
down_revision = 'cfbba8e8e9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
